In [1]:
import numpy as np

In [118]:
vector=np.zeros(10)
vector[4]=1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [50]:
vector1=np.arange(10,50)
vector1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [65]:
np.flip(vector1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [94]:
y=np.arange(0,9,1)
y=y.reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
rand=np.random.rand(3,3,3)

In [43]:
rand

array([[[0.52651354, 0.53301902, 0.49812172],
        [0.88492231, 0.84815599, 0.69532643],
        [0.24021769, 0.51667199, 0.0310299 ]],

       [[0.0261668 , 0.96940338, 0.51880263],
        [0.07048596, 0.81631839, 0.93439262],
        [0.69896866, 0.70764819, 0.16267167]],

       [[0.05430397, 0.66602049, 0.34384697],
        [0.31017899, 0.97234303, 0.14700405],
        [0.17647445, 0.5139509 , 0.1761329 ]]])

In [70]:
rand1=np.random.rand(10,10)
print(np.max(rand1))
print(np.min(rand1))

0.9830849771781393
0.005277852485274015


In [95]:
nz=[1,2,0,0,4,0]
np.nonzero(nz)

(array([0, 1, 4]),)

In [96]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])